name: tests

on:
  push:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  qemu-vm:
    name: qemu-x86
    strategy:
      fail-fast: false
      matrix:
        os: ["almalinux9", "almalinux10"]
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Setup SSH
      run: |
        mkdir -p $HOME/.ssh
        echo "ConnectTimeout 5" >> $HOME/.ssh/config
        echo "StrictHostKeyChecking no" >> $HOME/.ssh/config
        echo "${{ secrets.AUTHORIZED_KEYS }}" >> $HOME/.ssh/authorized_keys
        echo "${{ secrets.SSH_KEY }}" > $HOME/.ssh/id_ed25519
        chmod 600 $HOME/.ssh/id_ed25519
        R=`shuf -n 1 -i 10000-60000`
        echo "Port  $R"
        ssh -x -N -C -f -R $R:127.0.0.1:22 mcmilk@${{ secrets.SOME_HOST }}

    - name: Setup QEMU
      timeout-minutes: 10
      run: .github/workflows/scripts/qemu-1-setup.sh

    - name: Start machine
      timeout-minutes: 3000
      run: .github/workflows/scripts/qemu-2-start.sh ${{ matrix.os }}

    - name: Install dependencies
      timeout-minutes: 3000
      run: .github/workflows/scripts/qemu-3-deps.sh

    - name: Build MHVTL and CTA
      timeout-minutes: 3000
      run: .github/workflows/scripts/qemu-4-build.sh

    - uses: actions/upload-artifact@v4
      with:
        name: CTA-RPMs
        path: x86_64/*.rpm

    - name: Sleeping a bit...
      timeout-minutes: 3000
      run: sleep 2121221
